void init_ppu(void);
void ppu_write_reg1(unsigned int);
void ppu_write_reg2(unsigned int);
void ppu(unsigned int);
void ppu_write_addr(unsigned int);
void ppu_write_data(unsigned int);
void ppu_addr_reset_count(void);
unsigned int ppu_read_reg2(void);
void ppu_set_bank(unsigned int, unsigned int);
void ppu_writeb_unsafe(unsigned int, unsigned char);
unsigned char ppu_readb_unsafe(unsigned int);
void ppu_set_writeb(void (*)(unsigned int, unsigned char));
void ppu_set_readb(unsigned char (*)(unsigned int));
